# Generated by Django 4.2.7 on 2025-10-23 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportDetailed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("air", "Air Quality"), ("noise", "Noise Level")],
                        max_length=10,
                    ),
                ),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                (
                    "air_quality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("good", "Good"),
                            ("moderate", "Moderate"),
                            ("unhealthy", "Unhealthy"),
                            ("very_unhealthy", "Very Unhealthy"),
                            ("hazardous", "Hazardous"),
                        ],
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "noise_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("quiet", "Quiet"),
                            ("moderate", "Moderate"),
                            ("loud", "Loud"),
                            ("very_loud", "Very Loud"),
                        ],
                        max_length=25,
                        null=True,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("audio_url", models.URLField(blank=True, null=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("upvote", models.IntegerField(default=0)),
                ("downvote", models.IntegerField(default=0)),
                (
                    "userVote",
                    models.CharField(
                        choices=[("up", "Up"), ("down", "Down")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-create_at"],
            },
        ),
    ]
