# Generated by Django 5.2.7 on 2025-10-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AqiPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(db_index=True)),
                ('lon', models.FloatField(db_index=True)),
                ('aqi', models.IntegerField(default=1)),
                ('pm25', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('lat', 'lon')},
            },
        ),
    ]
