# Generated by Django 4.2.7 on 2025-10-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="location",
        ),
        migrations.AddField(
            model_name="user",
            name="lat",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="lng",
            field=models.IntegerField(null=True),
        ),
    ]
