# Generated by Django 5.2.7 on 2025-10-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_location_user_lat_user_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_reports',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/avatars/'),
        ),
    ]
