name: Backend CI

on:
  push:
    branches: [ CICD ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  lint-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend
        shell: bash

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
  
      - name: Install Dependencies and Lint
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      # - name: Run Lint
      #   run: flake8 .

      - name: Run Django health checks
        run: |
          python manage.py check
          if python manage.py showmigrations --plan | grep '\[ \]'; then
            python manage.py migrate --noinput
          else
            python manage.py migrate --check
          fi

      - name: Run Django Tests
        run: python manage.py test