name: Database Setup

on:
  push:
    branches: [ CICD ]
  pull_request:
    branches: [ main ]

jobs:
  create-database:
    runs-on: ubuntu-latest    
    steps:
        - name: Check out repository code
          uses: actions/checkout@v4

        - name: Setup Database
          run: |
            docker compose up -d