name: Frontend CI
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
jobs:
  lint-frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend
        shell: bash

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Setup NodeJS 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install and Lint
        run: |
          npm install
          npm run lint
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      - name: Show status
        if: always()
        run: echo "🍏 This job's status is ${{ job.status }}."